### ISSUE TITLE
Improve performance pleaseeee

### ISSUE THREAD

**Issue by Mistium** [ThePandaDever/Flufi-OS#2]
Fibonacci 1000th number speed test:

# Times

OSL: 30ms

OASM: 0.6ms

BASE FSL: 1500ms (best case)

FSL (using oasm): 27ms

# Explanation

I honestly think if I did use fsl id just run oasm for most functions (especially maths and big calculations).

Unless you will be using some kind of cached rendering system, FSL will run into some genuine issues with performance if you need to run the psl parser to render ui elements or gui in general. Its better to make the system as fast as possible early on so that you have a template for how to make it later.

**Comment by Mistium** [comment]
i can always help out with optimising :)

**Comment by ThePandaDever** [comment]
true yea i do want to add caching, i think a big problem is parsing the script itself, as its soo slow but then i want to cache some of the stuff it pulls from runtime and probably get it to swap to a different way of storing stuff idk

**Comment by ThePandaDever** [comment]
i might make it compile to a secondary format hidden somewhere, that would be fully parsed and a saved env and such that it can just pull from and run it without having to do any parsing at all

**Comment by Mistium** [comment]
ill boot up the performance analyser to see what parts are taking the longest so you have some more information on what might need some effort into it

**Comment by ThePandaDever** [comment]
:3 please lmao

**Comment by ThePandaDever** [comment]
ill update the docs with the ++ and -- in 003

**Comment by Mistium** [comment]
> i might make it compile to a secondary format hidden somewhere, that would be fully parsed and a saved env and such that it can just pull from and run it without having to do any parsing at all

in theory this is great, but i was never able to do stuff like this in osl cos osl is runtime based and needs to be parsed on the fly

**Comment by ThePandaDever** [comment]
luckly i designed fsl do be split into phases:
* Preparsing (finding functions)
* Parsing
* Execution

**Comment by Mistium** [comment]
OK, firstly, 40% of your time is spent setting json keys

**Comment by ThePandaDever** [comment]
LMAOOOOOOOO yea
